-- populate_example_data.sql
-- Script to populate debug_marathon database with realistic example data

USE `debug_marathon`;

-- 1. Insert Users (15 total)
-- Password: 'Password123!' (hashed using SHA256 for demonstration)
-- In a real app, these would be bcrypt hashes generated by the backend.
INSERT INTO `users` (`username`, `email`, `password_hash`, `full_name`, `role`, `registration_date`) VALUES
('admin1', 'admin1@debugmarathon.com', SHA2('Password123!', 256), 'Main Administrator', 'admin', NOW() - INTERVAL 30 DAY),
('admin2', 'admin2@debugmarathon.com', SHA2('Password123!', 256), 'Secondary Admin', 'admin', NOW() - INTERVAL 25 DAY),
('participant1', 'participant1@example.com', SHA2('Password123!', 256), 'John Doe', 'participant', NOW() - INTERVAL 20 DAY),
('participant2', 'participant2@example.com', SHA2('Password123!', 256), 'Jane Smith', 'participant', NOW() - INTERVAL 19 DAY),
('participant3', 'participant3@example.com', SHA2('Password123!', 256), 'Mike Ross', 'participant', NOW() - INTERVAL 18 DAY),
('participant4', 'participant4@example.com', SHA2('Password123!', 256), 'Rachel Zane', 'participant', NOW() - INTERVAL 17 DAY),
('participant5', 'participant5@example.com', SHA2('Password123!', 256), 'Harvey Specter', 'participant', NOW() - INTERVAL 16 DAY),
('participant6', 'participant6@example.com', SHA2('Password123!', 256), 'Donna Paulsen', 'participant', NOW() - INTERVAL 15 DAY),
('participant7', 'participant7@example.com', SHA2('Password123!', 256), 'Louis Litt', 'participant', NOW() - INTERVAL 14 DAY),
('participant8', 'participant8@example.com', SHA2('Password123!', 256), 'Jessica Pearson', 'participant', NOW() - INTERVAL 13 DAY),
('participant9', 'participant9@example.com', SHA2('Password123!', 256), 'Sheldon Cooper', 'participant', NOW() - INTERVAL 12 DAY),
('participant10', 'participant10@example.com', SHA2('Password123!', 256), 'Leonard Hofstadter', 'participant', NOW() - INTERVAL 11 DAY),
('participant11', 'participant11@example.com', SHA2('Password123!', 256), 'Penny Queen', 'participant', NOW() - INTERVAL 10 DAY),
('participant12', 'participant12@example.com', SHA2('Password123!', 256), 'Howard Wolowitz', 'participant', NOW() - INTERVAL 9 DAY),
('participant13', 'participant13@example.com', SHA2('Password123!', 256), 'Rajesh Koothrappali', 'participant', NOW() - INTERVAL 8 DAY);

-- 2. Insert Contests (2 total)
INSERT INTO `contests` (`contest_name`, `description`, `start_datetime`, `end_datetime`, `created_by`, `max_violations_allowed`, `status`) VALUES
('Summer Debug Marathon 2025', 'The annual summer challenge for debugging experts.', '2025-12-01 09:00:00', '2025-12-31 18:00:00', 1, 5, 'live'),
('Winter Debugging Championship 2026', 'A cold-blooded battle of code optimization.', '2026-01-15 10:00:00', '2026-02-15 17:00:00', 2, 3, 'draft');

-- 3. Insert Rounds (3 per contest)
-- Contest 1 Rounds
INSERT INTO `rounds` (`contest_id`, `round_name`, `round_number`, `time_limit_minutes`, `total_questions`, `passing_score`, `is_locked`, `status`) VALUES
(1, 'Easy Level', 1, 30, 10, 60.00, 0, 'active'),
(1, 'Medium Level', 2, 45, 8, 70.00, 1, 'pending'),
(1, 'Hard Level', 3, 60, 5, 75.00, 1, 'pending');

-- Contest 2 Rounds
INSERT INTO `rounds` (`contest_id`, `round_name`, `round_number`, `time_limit_minutes`, `total_questions`, `passing_score`, `is_locked`, `status`) VALUES
(2, 'Easy Level', 1, 30, 10, 60.00, 0, 'pending'),
(2, 'Medium Level', 2, 45, 8, 70.00, 1, 'pending'),
(2, 'Hard Level', 3, 60, 5, 75.00, 1, 'pending');

-- 4. Insert Questions (Example for Contest 1 Round 1 - Easy)
INSERT INTO `questions` (`round_id`, `question_number`, `question_title`, `question_description`, `buggy_code`, `expected_output`, `test_cases`, `difficulty_level`, `points`, `time_estimate_minutes`) VALUES
(1, 1, 'Fix the Infinite Loop', 'This function should print numbers 1-10 but runs infinitely because the counter is not incremented.', 'def print_numbers():\n    i = 1\n    while i <= 10:\n        print(i)', '1\n2\n3\n4\n5\n6\n7\n8\n9\n10', '{"cases": [{"input": "", "expected": "1\\n2\\n3\\n4\\n5\\n6\\n7\\n8\\n9\\n10"}]}', 'easy', 10, 5),
(1, 2, 'Off-by-One Error', 'The sum function skips the last number. Fix the loop range.', 'def get_sum(n):\n    total = 0\n    for i in range(n):\n        total += i\n    return total', '15', '{"cases": [{"input": "5", "expected": "15"}]}', 'easy', 10, 5),
(1, 3, 'Missing Return', 'This function should return the maximum of two numbers but returns None.', 'def get_max(a, b):\n    if a > b:\n        res = a\n    else:\n        res = b', '10', '{"cases": [{"input": "10, 5", "expected": "10"}]}', 'easy', 10, 3),
(1, 4, 'Variable Scope Issue', 'Correct the variable assignment error.', 'count = 0\ndef increment():\n    count = count + 1\n    return count', '1', '{"cases": [{"input": "", "expected": "1"}]}', 'easy', 10, 5),
(1, 5, 'Type Conversion', 'The code fails to add a string and integer.', 'def add_values(a, b):\n    return a + b', '15', '{"cases": [{"input": "10, \'5\'", "expected": "15"}]}', 'easy', 10, 3),
(1, 6, 'Logic Error', 'Function should return True only if both are positive.', 'def both_positive(a, b):\n    return a > 0 or b > 0', 'False', '{"cases": [{"input": "-1, 5", "expected": "False"}]}', 'easy', 10, 4),
(1, 7, 'Syntax Mistake', 'Fix the missing colon in this function definition.', 'def check_even(n)\n    if n % 2 == 0:\n        return True\n    return False', 'True', '{"cases": [{"input": "4", "expected": "True"}]}', 'easy', 10, 2),
(1, 8, 'Array Index Error', 'Handle the case for empty arrays to prevent out of bounds.', 'def get_first(arr):\n    return arr[0]', 'None', '{"cases": [{"input": "[]", "expected": "None"}]}', 'easy', 10, 4),
(1, 9, 'Condition Check', 'Ensure the square root is only taken for non-negative numbers.', 'import math\ndef get_sqrt(n):\n    return math.sqrt(n)', 'Error', '{"cases": [{"input": "-4", "expected": "Error"}]}', 'easy', 10, 5),
(1, 10, 'String Manipulation', 'Concatenate first and last name with a space.', 'def full_name(f, l):\n    return f + l', 'John Doe', '{"cases": [{"input": "\'John\', \'Doe\'", "expected": "John Doe"}]}', 'easy', 10, 3);

-- 5. Insert Submissions (Example data for participants)
INSERT INTO `submissions` (`user_id`, `question_id`, `round_id`, `contest_id`, `submitted_code`, `time_taken_seconds`, `is_correct`, `score_awarded`, `status`) VALUES
(3, 1, 1, 1, 'def print_numbers():\n    i = 1\n    while i <= 10:\n        print(i)\n        i += 1', 120, 1, 10.00, 'evaluated'),
(3, 2, 1, 1, 'def get_sum(n):\n    total = 0\n    for i in range(n+1):\n        total += i\n    return total', 150, 1, 10.00, 'evaluated'),
(4, 1, 1, 1, 'def print_numbers():\n    i = 1\n    while i <= 10:\n        print(i)\n        i += 1', 90, 1, 10.00, 'evaluated'),
(5, 1, 1, 1, 'def print_numbers():\n    while i < 10: pass', 300, 0, 0.00, 'failed'),
(6, 1, 1, 1, 'def print_numbers():\n    i = 1\n    while i <= 10:\n        print(i)\n        i += 1', 45, 1, 10.00, 'evaluated');

-- 6. Insert Violations
INSERT INTO `violations` (`user_id`, `contest_id`, `round_id`, `question_id`, `violation_type`, `violation_description`, `severity`, `ip_address`) VALUES
(5, 1, 1, 1, 'tab_switch', 'Participant switched browser tab', 'medium', '192.168.1.105'),
(5, 1, 1, 1, 'copy_attempt', 'Attempted to copy from restricted area', 'high', '192.168.1.105'),
(7, 1, 1, 2, 'right_click', 'Right-click context menu triggered', 'low', '192.168.1.107'),
(9, 1, 1, 3, 'esc_key', 'Manual exit attempt via ESC key', 'critical', '192.168.1.109');

-- 7. Insert Leaderboard (Initial calculation)
INSERT INTO `leaderboard` (`user_id`, `contest_id`, `total_score`, `total_time_taken_seconds`, `questions_attempted`, `questions_correct`, `violations_count`, `current_round`, `rank_position`) VALUES
(3, 1, 20.00, 270, 2, 2, 0, 1, 1),
(4, 1, 10.00, 90, 1, 1, 0, 1, 2),
(6, 1, 10.00, 45, 1, 1, 0, 1, 3),
(5, 1, 0.00, 300, 1, 0, 2, 1, 4);
